### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by evertiro** [mat2252/helpscout-fluid-app#1]
I'm not sure why, but this doesn't seem to be working. I've tried using `*secure.helpscout.net*` and `secure.helpscout.net` but it never triggers. I've even tried a blank userscript with those patterns that does nothing but `console.log('test');`. Thoughts?

**Comment by evertiro** [comment]
Nevermind. Force kill the app and restart and it works!

**Comment by mat2252** [comment]
All right ! Let me know if you have other issues.

Thanks for checking out GitHub stuff !
